version: "3"
services:
  app:
    container_name: afs
    restart: always
    build: .
    ports:
      - "3001:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
		env_file:
			- .env
    ports:
      - "27017:27017"

networks: 
	avigo_net:
		external: 
			name: $EXTERNAL_NETWORK